# Use the official PHP 8.3-FPM image as the base
FROM php:8.3-fpm

# Set environment variables for non-interactive installation
ENV DEBIAN_FRONTEND=noninteractive

# Install system dependencies
RUN apt-get update && apt-get install -y \
    libfreetype6-dev \
    libjpeg62-turbo-dev \
    libpng-dev \
    libzip-dev \
    libicu-dev \
    libldap2-dev \
    libonig-dev \
    libcurl4-openssl-dev \
    libc-client-dev \
    libkrb5-dev \
    unzip \
    git \
    curl \
    && docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-install -j$(nproc) gd \
    && docker-php-ext-install mysqli pdo pdo_mysql \
    && docker-php-ext-install exif intl mbstring curl ldap zip \
    && pecl install imap \
    && docker-php-ext-enable imap

# Install Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer


# Clean up
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

# Set working directory
WORKDIR /var/www/html/espocrm

COPY ./ ./

RUN composer install


# && chown -R 33:33 .;
RUN find data -type d -exec chmod 775 {} +
RUN find data custom client/custom -type d -exec chmod 777 {} + && find data custom client/custom -type f -exec chmod 777 {} +;
RUN chmod 777 application/Espo/Modules client/modules;
RUN chmod 777 bin/command;

# Expose port 9000 for PHP-FPM
EXPOSE 9000

# Start PHP-FPM server
CMD ["php-fpm"]
